# base
seed: 1

# data
dataname: cub
num_classes: 40

# mncode
t_mix: 0.1

# model
model: pretrained-resnet18

# train
train_batch: 32
opt: sgd
epochs: 200
lr: 0.01
weight_decay: 5e-4
scheduler: cosine
steps: -1

# forget
forget_idx: [0]
lambda1: 1e-4
lambda2: 1.0

